### ISSUE TITLE
Change Origin.Type enum to be consistent with existing terminology.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.metrics#16]
Origin.Type uses the value `Operator` to describe custom metrics, why not just use `Custom` to be aligned with the existing terminology. I also wonder if the type can be simplified to just `MetricType` rather than wrapping in an Origin composite. I tend to find composite embedded types non-intuitive to use, so a simple type is clearer.

```
type MetricType = enum {
			Custom,
			OperatorInputPort,
			OperatorOutputPort,
                        PEInputPort,
                        PEOutputPort
		};
```

**Comment by m-kotowski** [comment]
The metric type is specified [here](http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.0.0/com.ibm.streams.jmxapi.doc/api/com/ibm/streams/management/MetricMetadata.Type.html). The metric type can be either `custom`, `system`, or `unknown`.

With the implementation of issue #15 we also provide the metric type as described above, which means the `rstring metricType` attribute gets on the following values: `custom`, `system`, or `unknown`.

The intention of the origin is different. It specifies whether the metric belongs to the operator directly, or to one of its input or output ports, etc. Therefore, I would keep the origin type as is.

Wrapped or non-wrapped types are probably a matter of taste. But, from my experience it is better to wrap them because you prevent name clashes. Also some standard types are wrapped in the the Sys composite, like Sys.Kind or Sys.LogLevel.

**Comment by m-kotowski** [comment]
Please reopen if needed.
